/* Generated by MyraPad at 12/16/2025 7:31:35 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace OpenGothic.Viewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_textBoxFilter = new TextBox();
			_textBoxFilter.HintText = "Filter";
			_textBoxFilter.Id = "_textBoxFilter";

			var label1 = new Label();
			label1.Text = "*.MSB";

			_checkMsbFilter = new CheckButton();
			_checkMsbFilter.IsChecked = true;
			_checkMsbFilter.CheckContentSpacing = 4;
			_checkMsbFilter.Id = "_checkMsbFilter";
			_checkMsbFilter.Content = label1;

			var label2 = new Label();
			label2.Text = "*.ZEN";

			_checkZenFilter = new CheckButton();
			_checkZenFilter.IsChecked = true;
			_checkZenFilter.CheckContentSpacing = 4;
			_checkZenFilter.Id = "_checkZenFilter";
			_checkZenFilter.Content = label2;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_checkMsbFilter);
			horizontalStackPanel1.Widgets.Add(_checkZenFilter);

			var horizontalSeparator1 = new HorizontalSeparator();

			_listItems = new ListView();
			_listItems.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listItems.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listItems.Id = "_listItems";
			StackPanel.SetProportionType(_listItems, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(_textBoxFilter);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_listItems);

			_panelViewer = new Panel();
			_panelViewer.Id = "_panelViewer";

			_labelCameraPosition = new Label();
			_labelCameraPosition.Text = "10, 10, 10";
			_labelCameraPosition.Left = -4;
			_labelCameraPosition.Top = 4;
			_labelCameraPosition.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_labelCameraPosition.Id = "_labelCameraPosition";

			var label3 = new Label();
			label3.Text = "/c[red]O/cdptions";

			_buttonOptions = new Button();
			_buttonOptions.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_buttonOptions.Id = "_buttonOptions";
			_buttonOptions.Content = label3;

			var panel1 = new Panel();
			panel1.Widgets.Add(_panelViewer);
			panel1.Widgets.Add(_labelCameraPosition);
			panel1.Widgets.Add(_buttonOptions);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(verticalStackPanel1);
			_topSplitPane.Widgets.Add(panel1);

			var label4 = new Label();
			label4.Text = "FPS:";

			var label5 = new Label();
			label5.Text = "Effects Switches:";
			Grid.SetRow(label5, 1);

			var label6 = new Label();
			label6.Text = "Draw Calls:";
			Grid.SetRow(label6, 2);

			var label7 = new Label();
			label7.Text = "Vertices Drawn:";
			Grid.SetRow(label7, 3);

			var label8 = new Label();
			label8.Text = "Primitives Drawn:";
			Grid.SetRow(label8, 4);

			var label9 = new Label();
			label9.Text = "Passes:";
			Grid.SetRow(label9, 5);

			_labelFPS = new Label();
			_labelFPS.Text = "10";
			_labelFPS.Id = "_labelFPS";
			Grid.SetColumn(_labelFPS, 1);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);
			Grid.SetRow(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 2);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 3);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 4);

			_labelPasses = new Label();
			_labelPasses.Text = "10";
			_labelPasses.Id = "_labelPasses";
			Grid.SetColumn(_labelPasses, 1);
			Grid.SetRow(_labelPasses, 5);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label4);
			_panelStatistics.Widgets.Add(label5);
			_panelStatistics.Widgets.Add(label6);
			_panelStatistics.Widgets.Add(label7);
			_panelStatistics.Widgets.Add(label8);
			_panelStatistics.Widgets.Add(label9);
			_panelStatistics.Widgets.Add(_labelFPS);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelPasses);

			
			Widgets.Add(_topSplitPane);
			Widgets.Add(_panelStatistics);
		}

		
		public TextBox _textBoxFilter;
		public CheckButton _checkMsbFilter;
		public CheckButton _checkZenFilter;
		public ListView _listItems;
		public Panel _panelViewer;
		public Label _labelCameraPosition;
		public Button _buttonOptions;
		public HorizontalSplitPane _topSplitPane;
		public Label _labelFPS;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelPasses;
		public Grid _panelStatistics;
	}
}
