/* Generated by MyraPad at 12/15/2025 4:34:16 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace OpenGothic.Viewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_textBoxFilter = new TextBox();
			_textBoxFilter.HintText = "Filter";
			_textBoxFilter.Id = "_textBoxFilter";

			var horizontalSeparator1 = new HorizontalSeparator();

			_listItems = new ListView();
			_listItems.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listItems.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listItems.Id = "_listItems";
			StackPanel.SetProportionType(_listItems, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(_textBoxFilter);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_listItems);

			_panelViewer = new Panel();
			_panelViewer.Id = "_panelViewer";

			_labelFPS = new Label();
			_labelFPS.Text = "FPS:";
			_labelFPS.Left = -4;
			_labelFPS.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_labelFPS.Id = "_labelFPS";

			var label1 = new Label();
			label1.Text = "/c[red]O/cdptions";

			_buttonOptions = new Button();
			_buttonOptions.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_buttonOptions.Id = "_buttonOptions";
			_buttonOptions.Content = label1;

			var panel1 = new Panel();
			panel1.Widgets.Add(_panelViewer);
			panel1.Widgets.Add(_labelFPS);
			panel1.Widgets.Add(_buttonOptions);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(verticalStackPanel1);
			_topSplitPane.Widgets.Add(panel1);

			var label2 = new Label();
			label2.Text = "Effects Switches:";

			var label3 = new Label();
			label3.Text = "Draw Calls:";
			Grid.SetRow(label3, 1);

			var label4 = new Label();
			label4.Text = "Vertices Drawn:";
			Grid.SetRow(label4, 2);

			var label5 = new Label();
			label5.Text = "Primitives Drawn:";
			Grid.SetRow(label5, 3);

			var label6 = new Label();
			label6.Text = "Passes:";
			Grid.SetRow(label6, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelPasses = new Label();
			_labelPasses.Text = "10";
			_labelPasses.Id = "_labelPasses";
			Grid.SetColumn(_labelPasses, 1);
			Grid.SetRow(_labelPasses, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label2);
			_panelStatistics.Widgets.Add(label3);
			_panelStatistics.Widgets.Add(label4);
			_panelStatistics.Widgets.Add(label5);
			_panelStatistics.Widgets.Add(label6);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelPasses);

			
			Widgets.Add(_topSplitPane);
			Widgets.Add(_panelStatistics);
		}

		
		public TextBox _textBoxFilter;
		public ListView _listItems;
		public Panel _panelViewer;
		public Label _labelFPS;
		public Button _buttonOptions;
		public HorizontalSplitPane _topSplitPane;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelPasses;
		public Grid _panelStatistics;
	}
}
