/* Generated by MyraPad at 12/13/2025 10:45:16 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace OpenGothic.Viewer.UI
{
	partial class ModelViewerPanel: Panel
	{
		private void BuildUI()
		{
			_panelModelViewer = new Panel();
			_panelModelViewer.Id = "_panelModelViewer";

			var label1 = new Label();
			label1.Text = "Animation:";

			var label2 = new Label();

			var label3 = new Label();
			label3.Text = "Move";

			var label4 = new Label();
			label4.Text = "Attack";

			_comboAnimations = new ComboView();
			_comboAnimations.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboAnimations.Id = "_comboAnimations";
			Grid.SetColumn(_comboAnimations, 1);
			_comboAnimations.Widgets.Add(label2);
			_comboAnimations.Widgets.Add(label3);
			_comboAnimations.Widgets.Add(label4);

			var label5 = new Label();
			label5.Text = "Mode:";
			Grid.SetRow(label5, 1);

			var label6 = new Label();
			label6.Text = "Forward";

			var label7 = new Label();
			label7.Text = "Backward";

			_comboPlaybackMode = new ComboView();
			_comboPlaybackMode.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboPlaybackMode.Id = "_comboPlaybackMode";
			Grid.SetColumn(_comboPlaybackMode, 1);
			Grid.SetRow(_comboPlaybackMode, 1);
			_comboPlaybackMode.Widgets.Add(label6);
			_comboPlaybackMode.Widgets.Add(label7);

			var label8 = new Label();
			label8.Text = "Speed:";
			Grid.SetRow(label8, 2);

			_sliderSpeed = new HorizontalSlider();
			_sliderSpeed.Minimum = 0.1f;
			_sliderSpeed.Maximum = 3;
			_sliderSpeed.Value = 1;
			_sliderSpeed.Id = "_sliderSpeed";
			StackPanel.SetProportionType(_sliderSpeed, Myra.Graphics2D.UI.ProportionType.Fill);

			_labelSpeed = new Label();
			_labelSpeed.Text = "1.0";
			_labelSpeed.Width = 40;
			_labelSpeed.Id = "_labelSpeed";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel1, 1);
			Grid.SetRow(horizontalStackPanel1, 2);
			horizontalStackPanel1.Widgets.Add(_sliderSpeed);
			horizontalStackPanel1.Widgets.Add(_labelSpeed);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 300,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_comboAnimations);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(_comboPlaybackMode);
			grid1.Widgets.Add(label8);
			grid1.Widgets.Add(horizontalStackPanel1);

			var label9 = new Label();
			label9.Text = "Crossfade";

			_checkCrossfade = new CheckButton();
			_checkCrossfade.IsChecked = true;
			_checkCrossfade.CheckContentSpacing = 8;
			_checkCrossfade.Id = "_checkCrossfade";
			_checkCrossfade.Content = label9;

			var label10 = new Label();
			label10.Text = "Play";

			_buttonPlayStop = new Button();
			_buttonPlayStop.Width = 100;
			_buttonPlayStop.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_buttonPlayStop.Id = "_buttonPlayStop";
			_buttonPlayStop.Content = label10;

			_sliderTime = new HorizontalSlider();
			_sliderTime.Width = 300;
			_sliderTime.Id = "_sliderTime";

			_labelTime = new Label();
			_labelTime.Text = "0.0";
			_labelTime.Id = "_labelTime";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(_buttonPlayStop);
			horizontalStackPanel2.Widgets.Add(_sliderTime);
			horizontalStackPanel2.Widgets.Add(_labelTime);

			var label11 = new Label();
			label11.Text = "Draw Bounding Boxes";

			_checkDrawBoundingBoxes = new CheckButton();
			_checkDrawBoundingBoxes.CheckContentSpacing = 8;
			_checkDrawBoundingBoxes.Id = "_checkDrawBoundingBoxes";
			_checkDrawBoundingBoxes.Content = label11;

			var label12 = new Label();
			label12.Text = "Disable Normal Mapping";

			_checkDisableNormalMapping = new CheckButton();
			_checkDisableNormalMapping.CheckContentSpacing = 8;
			_checkDisableNormalMapping.Id = "_checkDisableNormalMapping";
			_checkDisableNormalMapping.Content = label12;

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Spacing = 8;
			horizontalStackPanel3.Widgets.Add(_checkDrawBoundingBoxes);
			horizontalStackPanel3.Widgets.Add(_checkDisableNormalMapping);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(_checkCrossfade);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel3);

			var label13 = new Label();
			label13.Text = "Effects Switches:";

			var label14 = new Label();
			label14.Text = "Draw Calls:";
			Grid.SetRow(label14, 1);

			var label15 = new Label();
			label15.Text = "Vertices Drawn:";
			Grid.SetRow(label15, 2);

			var label16 = new Label();
			label16.Text = "Primitives Drawn:";
			Grid.SetRow(label16, 3);

			var label17 = new Label();
			label17.Text = "Passes:";
			Grid.SetRow(label17, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelPasses = new Label();
			_labelPasses.Text = "10";
			_labelPasses.Id = "_labelPasses";
			Grid.SetColumn(_labelPasses, 1);
			Grid.SetRow(_labelPasses, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label13);
			_panelStatistics.Widgets.Add(label14);
			_panelStatistics.Widgets.Add(label15);
			_panelStatistics.Widgets.Add(label16);
			_panelStatistics.Widgets.Add(label17);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelPasses);

			
			Widgets.Add(_panelModelViewer);
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(_panelStatistics);
		}

		
		public Panel _panelModelViewer;
		public ComboView _comboAnimations;
		public ComboView _comboPlaybackMode;
		public HorizontalSlider _sliderSpeed;
		public Label _labelSpeed;
		public CheckButton _checkCrossfade;
		public Button _buttonPlayStop;
		public HorizontalSlider _sliderTime;
		public Label _labelTime;
		public CheckButton _checkDrawBoundingBoxes;
		public CheckButton _checkDisableNormalMapping;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelPasses;
		public Grid _panelStatistics;
	}
}
