/* Generated by MyraPad at 11/22/2025 10:06:50 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace OpenGothic.UI
{
	partial class OptionsWindow: Window
	{
		private void BuildUI()
		{
			_propertiesGraphics = new PropertyGrid();
			_propertiesGraphics.Id = "_propertiesGraphics";

			var tabItem1 = new TabItem();
			tabItem1.Text = "Graphics";
			tabItem1.Content = _propertiesGraphics;

			_propertiesDebug = new PropertyGrid();
			_propertiesDebug.Id = "_propertiesDebug";

			var tabItem2 = new TabItem();
			tabItem2.Text = "Debug";
			tabItem2.Content = _propertiesDebug;

			_propertiesEnvironment = new PropertyGrid();
			_propertiesEnvironment.Id = "_propertiesEnvironment";

			var tabItem3 = new TabItem();
			tabItem3.Text = "Environment";
			tabItem3.Content = _propertiesEnvironment;

			var tabControl1 = new TabControl();
			tabControl1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			tabControl1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			tabControl1.Items.Add(tabItem1);
			tabControl1.Items.Add(tabItem2);
			tabControl1.Items.Add(tabItem3);

			
			Title = "Options";
			Left = 464;
			Top = 78;
			Width = 600;
			Height = 500;
			Content = tabControl1;
		}

		
		public PropertyGrid _propertiesGraphics;
		public PropertyGrid _propertiesDebug;
		public PropertyGrid _propertiesEnvironment;
	}
}
